import type { TranslationContent } from './types';

export const heroImages = [
  '/images/hero/l_albir_d2ae8820d05f96bc7f7d33001aaf5564.webp',
  '/images/hero/Cumbre-del-Sol-Calpe-Costa-Blanca-3-1920x1080.webp',
  '/images/hero/Cycling-calpe-and-costa-blanca-copyright-Sierras-Sports-Tours-3-1920x1080.webp',
];

export const copy: Record<'nl' | 'en' | 'es', TranslationContent> = {
  nl: {
    nav: { home: 'Home', story: 'Het Verhaal', route: 'De Route', terro: 'Project Terro', blog: 'Blog', donate: 'Doneren', contact: 'Contact' },
    support: 'STEUN HET GOEDE DOEL & DONEER NU',
    heroEyebrow: 'FIETSUITDAGING VOOR HET GOED DOEL',
    heroTitle: 'PROJECT 10/70',
    heroText: 'Tien dagen. Zeventig jaar jong. Eén uitdaging die alles verandert.',
    discover: 'Ontdek het project',
    introOfficial: "In 2029 viert wielerteam Forza Fortuna (vzw) haar 10-jarig jubileum en bereik ik de legendarische leeftijd van 70 jaar. Twee unieke mijlpalen, één extreme uitdaging. Met Project 10/70 kruip ik 10 dagen lang in het zadel voor het goede doel: +17.000 hoogtemeters in de Spaanse bergen rondom L'Albir. Bewijzen dat leeftijd slechts een getal is.",
    stats: [['10', 'DAGEN IN HET ZADEL', 'story'], ['+17.000', 'HOOGTEMETERS', 'route'], ['70', 'JAAR JONG VAN GEEST', 'terro']],
    sponsorText: 'Fortuna Financial Group is één van de belangrijkste vermogensbegeleiders op de Belgische markt. CEO Frank Peeraer is een ex-profvoetballer met een echt sporthart en net als diverse van zijn medewerkers, zelf fervent fietser. Fortuna ondersteunt als bedrijf dan ook voluit het fietstoerisme én met trots Project 10/70.',
    sponsorLink: 'Ga naar Fortuna Financial Group',
    sponsorCards: [['Persoonlijk', 'Een aanpak die vertrekt vanuit mensen, doelen en dromen.'], ['Onafhankelijk', 'Heldere keuzes, zonder ruis. Altijd met jouw toekomst voorop.'], ['Een familiebedrijf', 'Vertrouwen en betrokkenheid, generatie na generatie.']],
    storyTitle: 'Van wielerpassie tot extreme uitdaging',
    storyLead: `In 2019 ontstond de vernieuwde vzw van wielerteam Forza Fortuna vanuit de pure wielerpassie op kantoor van Fortuna Financial Group en binnen de community. Wat begon als vriendschappelijke ritten op zondagochtend, groeide uit tot een hecht team met een gezamenlijke missie: passie, discipline en vriendschap verbinden op en naast de fiets.

Tien jaar later, in 2029, viert de vzw haar 10-jarig jubileum. Datzelfde jaar bereik ik Roel — beter bekend als "Terro" — de legendarische leeftijd van 70 jaar. Twee unieke mijlpalen die om een bijzonder verhaal vragen.

Dat verhaal werd Project 10/70: een extreme wieleruitdaging waarbij Terro 10 dagen lang in het zadel kruipt om meer dan 17.000 hoogtemeters te bedwingen in de Spaanse bergen rondom L'Albir. Geen toevallige keuze — de bergen die al meer dan 15 jaar het toneel vormen van legendarische ritten en onvergetelijke vriendschappen.

Het doel? Bewijzen dat leeftijd slechts een getal is. Dat passie geen grens kent. En dat je met de juiste voorbereiding, de onverwoestbare mentaliteit en de juiste mensen om je heen elk lange-termijndoel kunt bereiken.

Maar dit project gaat niet alleen over fietsen. Het gaat over het goede doel. Elke meter die geklommen wordt, elke zweetdruppel die valt, draagt bij aan een missie die groter is dan de sport zelf. En daar kan jij deel van uitmaken.`,
    storySections: [['Van idee naar avontuur', 'Wat begon als een idee aan de keukentafel groeide uit tot een uitdaging die vrienden, partners en een heel team samenbrengt.'], ['Twee mijlpalen, één extremum', 'Tien jaar Forza Fortuna vzw. Zeventig jaar jong van geest. Twee cijfers die samen de lat op 17.000 hoogtemeters leggen.'], ['Samen trappen', 'Elke kilometer krijgt meer betekenis wanneer we hem delen. Met supporters langs de weg, met donateurs op afstand en met het goede doel als kompas.']],
    routeTitle: 'De route',
    routeLead: 'Tien dagen door de ruige schoonheid van de Costa Blanca. Open een etappe voor het parcours en de live kaart.',
    stages: ['Coll de Rates Lus', 'La Vall d\'Ebo-pas & Coll de Rates', 'Altea — Guadalest', 'Cumbre del Sol', 'Vall de Gallinera', 'Bernia — Xaló', 'Sierra de Aitana', 'Parcent — Tarbena', 'De laatste klim', 'De finishrit'],
    routePlaceholder: 'Etappeprofiel wordt live gegenereerd tijdens de uitdaging in Spanje.',
    terroTitle: 'PROJECT 70: DE MAN ACHTER TERRO',
    terroSections: [['Wie is Terro?', 'Achter elke krachtige uitdaging staat een mens met een verhaal. Terro combineert ervaring, humor en een ontembare drang om te blijven bewegen.'], ['Twee mijlpalen, één extremum', 'Het getal 70 is geen eindpunt. Het is een startlijn voor een nieuw hoofdstuk vol hoogte, tegenwind en verbondenheid.'], ['De filosofie', 'Niet wachten op het perfecte moment. Gewoon de eerste trap geven, het peloton vinden en samen verder gaan.'], ['De voorbereiding', 'Met discipline, nieuwsgierigheid en een gezonde dosis respect voor de bergen wordt elke training een stukje van de route.']],
    blogTitle: 'Nieuws uit het peloton',
    blogLead: 'Updates, verhalen en momenten onderweg naar Project 10/70.',
    blogCards: [['Aankondiging', 'De eerste hoogtemeters zijn gemaakt'], ['Training', 'Waarom elke klim begint met een keuze'], ['Team', 'Forza Fortuna maakt zich klaar voor Spanje']],
    donateTitle: 'Klim mee naar 17.000',
    donateLead: 'Elke euro is één hoogtemeter. Elke hoogtemeter brengt ons dichter bij een toekomst voor het goede doel.',
    donated: 'Al',
    sponsored: 'van de 17.000 hoogtemeters gesponsord!',
    goal: 'Doel: 17.000 hm',
    donateIntro: 'Elke donatie maakt het verschil. Help ons bewijzen dat leeftijd slechts een getal is! Ter ere van het 10-jarig jubileum van Forza Fortuna vzw en mijn 70e verjaardag overwinnen wij +17.000 Spaanse hoogtemeters voor de toekomst van het goede doel.',
    donationForm: 'Donatieformulier',
    choose: 'Kies je donatie',
    name: 'Naam',
    message: 'Bericht (optioneel)',
    donateNow: 'Doneer en koop hoogtemeters',
    recent: 'Recente donateurs',
    noDonors: 'Jouw naam kan hier straks tussen staan.',
    tiers: [['Berggeit', '€10', '10 hm'], ['Klimmer', '€25', '25 hm'], ['Koning van de Berg', '€50', '50 hm'], ['Legende', '€100+', '100+ hm']],
    contactTitle: 'Neem contact op',
    contactLead: 'Een vraag, een idee of zin om mee te trappen? We horen graag van je.',
    send: 'Verstuur bericht',
    sent: 'Bedankt. We nemen zo snel mogelijk contact met je op.',
    email: 'Officieel e-mailadres'
  },
  en: {
    nav: { home: 'Home', story: 'The Story', route: 'The Route', terro: 'Project Terro', blog: 'Blog', donate: 'Donate', contact: 'Contact' },
    support: 'SUPPORT THE GOOD CAUSE & DONATE NOW',
    heroEyebrow: 'THE ULTIMATE CYCLING CHALLENGE',
    heroTitle: 'PROJECT 10/70',
    heroText: 'Ten days. Seventy years young. One ride that changes everything.',
    discover: 'Discover the project',
    introOfficial: "In 2029, cycling team Forza Fortuna (vzw) celebrates its 10th anniversary and I reach the legendary age of 70. Two unique milestones, one extreme challenge. With Project 10/70 I will spend 10 days in the saddle for a good cause: +17,000 vertical meters in the Spanish mountains around L'Albir. Proving that age is just a number.",
    stats: [['10', 'DAYS IN THE SADDLE', 'story'], ['+17,000', 'VERTICAL METERS', 'route'], ['70', 'YEARS YOUNG AT HEART', 'terro']],
    sponsorText: 'Fortuna Financial Group is one of the leading wealth managers in the Belgian market. CEO Frank Peeraer is a former professional footballer with a true sporting heart and, like several of his colleagues, an avid cyclist. Fortuna fully supports cycling tourism and proudly supports Project 10/70.',
    sponsorLink: 'Visit Fortuna Financial Group',
    sponsorCards: [['Personal', 'An approach built around people, goals and dreams.'], ['Independent', 'Clear choices, without the noise. Your future comes first.'], ['A family business', 'Trust and commitment, generation after generation.']],
    storyTitle: 'The story behind the challenge',
    storyLead: 'Project 10/70 is more than a bike ride. It is a personal promise, a sporting mission and a warm gesture to the causes that inspire us along the way.',
    storySections: [['From idea to adventure', 'What started as a kitchen-table idea became a challenge that brings friends, partners and a whole team together.'], ['Two milestones, one extreme', 'Ten years of Forza Fortuna vzw. Seventy years young at heart. Two numbers that set the bar at 17,000 vertical meters.'], ['Pedal together', 'Every kilometer becomes more meaningful when we share it. With supporters along the way, with donors from a distance, and with the good cause as our compass.']],
    routeTitle: 'The route',
    routeLead: 'Ten days through the rugged beauty of the Costa Blanca. Open a stage for the route and live map.',
    stages: ['Coll de Rates Loop', 'La Vall d\'Ebo-pass & Coll de Rates', 'Altea — Guadalest', 'Cumbre del Sol', 'Vall de Gallinera', 'Bernia — Xaló', 'Sierra de Aitana', 'Parcent — Tarbena', 'The final climb', 'The finish stage'],
    routePlaceholder: 'Stage profile will be generated live during the challenge in Spain.',
    terroTitle: 'PROJECT 70: THE MAN BEHIND TERRO',
    terroSections: [['Who is Terro?', 'Behind every powerful challenge is a person with a story. Terro combines experience, humor and an irrepressible drive to keep moving.'], ['Two milestones, one extreme', 'The number 70 is not an endpoint. It is a starting line for a new chapter full of altitude, headwind and connection.'], ['The philosophy', 'Don\'t wait for the perfect moment. Just take the first pedal, find the peloton and keep going together.'], ['The preparation', 'With discipline, curiosity and a healthy respect for the mountains, every training becomes a piece of the route.']],
    blogTitle: 'News from the peloton',
    blogLead: 'Updates, stories and moments on the way to Project 10/70.',
    blogCards: [['Announcement', 'The first vertical meters are made'], ['Training', 'Why every climb starts with a choice'], ['Team', 'Forza Fortuna is preparing for Spain']],
    donateTitle: 'Climb with us to 17,000',
    donateLead: 'Every euro is one vertical meter. Every vertical meter brings us closer to a future for the good cause.',
    donated: 'Already',
    sponsored: 'of the 17,000 vertical meters sponsored!',
    goal: 'Goal: 17,000 vm',
    donateIntro: 'Every donation makes a difference. Help us prove that age is just a number! In honor of the 10th anniversary of Forza Fortuna vzw and my 70th birthday, we will overcome +17,000 Spanish vertical meters for the future of the good cause.',
    donationForm: 'Donation form',
    choose: 'Choose your donation',
    name: 'Name',
    message: 'Message (optional)',
    donateNow: 'Donate and buy vertical meters',
    recent: 'Recent donors',
    noDonors: 'Your name can be here soon.',
    tiers: [['Mountain Goat', '€10', '10 vm'], ['Climber', '€25', '25 vm'], ['King of the Mountain', '€50', '50 vm'], ['Legend', '€100+', '100+ vm']],
    contactTitle: 'Get in touch',
    contactLead: 'A question, an idea or want to pedal along? We\'d love to hear from you.',
    send: 'Send message',
    sent: 'Thank you. We\'ll get back to you as soon as possible.',
    email: 'Official email address'
  },
  es: {
    nav: { home: 'Inicio', story: 'La historia', route: 'La ruta', terro: 'Proyecto Terro', blog: 'Blog', donate: 'Donar', contact: 'Contacto' },
    support: 'APOYA LA BUENA CAUSA & DONA AHORA',
    heroEyebrow: 'EL RETO CICLISTA DEFINITIVO',
    heroTitle: 'PROJECT 10/70',
    heroText: 'Diez días. Setenta años joven. Una ruta que lo cambia todo.',
    discover: 'Descubre el proyecto',
    introOfficial: "En 2029, el equipo ciclista Forza Fortuna (vzw) celebra su 10º aniversario y yo alcanzo la legendaria edad de 70 años. Dos hitos únicos, un reto extremo. Con el Proyecto 10/70 pasaré 10 días en el sillín por una buena causa: +17.000 metros de desnivel en las montañas españolas alrededor de L'Albir. Demostrando que la edad es solo un número.",
    stats: [['10', 'DÍAS EN EL SILLÍN', 'story'], ['+17.000', 'METROS DE DESNIVEL', 'route'], ['70', 'AÑOS JOVEN DE ESPÍRITU', 'terro']],
    sponsorText: 'Fortuna Financial Group es uno de los principales gestores patrimoniales del mercado belga. El CEO Frank Peeraer es un exfutbolista profesional con un gran corazón deportivo y, como varios de sus empleados, un ciclista apasionado. Fortuna apoya plenamente el cicloturismo y el Proyecto 10/70.',
    sponsorLink: 'Visita Fortuna Financial Group',
    sponsorCards: [['Personal', 'Un enfoque basado en personas, objetivos y sueños.'], ['Independiente', 'Decisiones claras, sin ruido. Tu futuro es lo primero.'], ['Una empresa familiar', 'Confianza y compromiso, generación tras generación.']],
    storyTitle: 'La historia detrás del reto',
    storyLead: 'Project 10/70 es más que una ruta en bicicleta. Es una promesa personal, una misión deportiva y un gesto hacia las causas que nos inspiran.',
    storySections: [['De la idea a la aventura', 'Lo que comenzó como una idea se convirtió en un reto que une a amigos, socios y todo un equipo.'], ['Dos hitos, un extremo', 'Diez años de Forza Fortuna vzw. Setenta años joven de espíritu. Dos números que marcan 17.000 metros de desnivel.'], ['Pedalear juntos', 'Cada kilómetro importa más cuando lo compartimos. Con seguidores en el camino, con donantes a distancia y con la buena causa como brújula.']],
    routeTitle: 'La ruta',
    routeLead: 'Diez días a través de la belleza salvaje de la Costa Blanca. Abre un tramo para el recorrido y el mapa en vivo.',
    stages: ['Bucle Coll de Rates', 'La Vall d\'Ebo-paso & Coll de Rates', 'Altea — Guadalest', 'Cumbre del Sol', 'Vall de Gallinera', 'Bernia — Xaló', 'Sierra de Aitana', 'Parcent — Tarbena', 'La última subida', 'La etapa final'],
    routePlaceholder: 'El perfil de la etapa se generará en vivo durante el reto en España.',
    terroTitle: 'PROYECTO 70: EL HOMBRE DETRÁS DE TERRO',
    terroSections: [['¿Quién es Terro?', 'Detrás de cada reto poderoso hay una persona con una historia. Terro combina experiencia, humor e un impulso irreprimible de seguir adelante.'], ['Dos hitos, un extremo', 'El número 70 no es un punto final. Es una línea de salida para un nuevo capítulo lleno de altitud, viento de frente y conexión.'], ['La filosofía', 'No esperes el momento perfecto. Solo toma el primer pedaleo, encuentra el pelotón y sigue adelante.'], ['La preparación', 'Con disciplina, curiosidad y un respeto saludable por las montañas, cada entrenamiento se convierte en una pieza de la ruta.']],
    blogTitle: 'Noticias del pelotón',
    blogLead: 'Actualizaciones, historias y momentos en el camino hacia el Proyecto 10/70.',
    blogCards: [['Anuncio', 'Los primeros metros de desnivel están hechos'], ['Entrenamiento', 'Por qué cada subida comienza con una elección'], ['Equipo', 'Forza Fortuna se prepara para España']],
    donateTitle: 'Sube con nosotros a 17.000',
    donateLead: 'Cada euro es un metro de desnivel. Cada metro de desnivel nos acerca a un futuro para la buena causa.',
    donated: 'Ya',
    sponsored: 'de los 17.000 metros de desnivel patrocinados!',
    goal: 'Meta: 17.000 md',
    donateIntro: 'Cada donación hace la diferencia. ¡Ayúdanos a demostrar que la edad es solo un número! En honor al 10º aniversario de Forza Fortuna vzw y mi 70º cumpleaños, superaremos +17.000 metros de desnivel españoles para el futuro de la buena causa.',
    donationForm: 'Formulario de donación',
    choose: 'Elige tu donación',
    name: 'Nombre',
    message: 'Mensaje (opcional)',
    donateNow: 'Dona y compra metros de desnivel',
    recent: 'Donantes recientes',
    noDonors: 'Tu nombre puede estar aquí pronto.',
    tiers: [['Cabra de montaña', '€10', '10 md'], ['Escalador', '€25', '25 md'], ['Rey de la montaña', '€50', '50 md'], ['Leyenda', '€100+', '100+ md']],
    contactTitle: 'Ponte en contacto',
    contactLead: '¿Una pregunta, una idea o ganas de pedalear? Nos encanta escucharte.',
    send: 'Enviar mensaje',
    sent: 'Gracias. Te responderemos lo antes posible.',
    email: 'Dirección de correo electrónico oficial'
  }
};
