export type Language = 'nl' | 'en' | 'es';
export type Page = 'home' | 'story' | 'route' | 'terro' | 'blog' | 'cause' | 'donate' | 'contact' | 'privacy';

export interface Donation {
  id: string;
  name: string;
  amount_eur: number;
  message: string;
  created_at: string;
}

export interface TranslationContent {
  nav: Record<'home' | 'story' | 'route' | 'terro' | 'blog' | 'cause' | 'donate' | 'contact', string>;
  support: string;
  heroEyebrow: [string, string];
  heroTitle: string;
  heroText: string;
  discover: string;
  introOfficial: string;
  stats: Array<[string, string, Page]>;
  sponsorText: string;
  sponsorLink: string;
  sponsorCards: Array<[string, string]>;
  storyTitle: string;
  storyLead: string;
  storyQuote: string;
  storyOutro: string;
  storySections: Array<[string, string]>;
  routeTitle: string;
  routeLead: string;
  stages: string[];
  routePlaceholder: string;
  routeViewer: {
    day: string;
    daysAria: string;
    loadingRoute: string;
    noRouteData: string;
    downloadGpx: string;
    distance: string;
    elevationGain: string;
    elevationLoss: string;
    maxGradient: string;
    lowestPoint: string;
    highestPoint: string;
    avgSpeed: string;
    estTime: string;
    ascent: string;
    descent: string;
    difficulty: string;
    speed: string;
    avgLabel: string;
    hard: string;
    moderate: string;
    easy: string;
    axisDistance: string;
    axisElevation: string;
    hoverHint: string;
    loadingGpx: string;
    noGpx: string;
    elevation: string;
    gradient: string;
    location: string;
    wayType: string;
    surface: string;
    surfaceValue: string;
    wayTypeValue: string;
    hourAbbr: string;
    weatherTitle: string;
    weatherToday: string;
    weatherTemp: string;
    weatherWind: string;
    weatherPrecip: string;
    weatherError: string;
    axisHint: string;
  };
  terroTitle: string;
  terroSections: Array<[string, string]>;
  causeTitle: string;
  causeLead: string;
  causeSections: Array<[string, string]>;
  causeLinkLabel: string;
  donateCauseTitle: string;
  donateCauseText: string;
  donateCauseLink: string;
  messageBlocked: string;
  nameInvalid: string;
  goalReached: string;
  blogTitle: string;
  blogLead: string;
  blogCards: Array<{ date: string; slug: string; label: string; title: string; fullTitle: string; body: string; postBody?: string; image?: string; status?: 'published' | 'upcoming'; expected?: string; stravaId?: string; stravaToken?: string; }>;
  donateTitle: string;
  donateLead: string;
  donated: string;
  sponsored: string;
  goal: string;
  donateIntro: string;
  donationForm: string;
  choose: string;
  name: string;
  message: string;
  donateNow: string;
  recent: string;
  noDonors: string;
  tiers: Array<[string, string, string]>;
  contactTitle: string;
  contactLead: string;
  send: string;
  sent: string;
  email: string;
}
